### ISSUE TITLE
ошибка при выполнении скрипта

### ISSUE THREAD

**Issue by ws23pro** [askkostya/EgaisMonitoring#3]
привет. при выполнении скрипта такая ошибка:

 File "C:\Users\utm\Desktop\EgaisMonitoring-master\getutminfo.py", line 29, in <module>
    if sys.argv[1] == "version":
IndexError: list index out of range

с чем связано?

**Comment by askkostya** [comment]
Не передан второй параметр 
Второй параметр может принимать значение 
version
rsavalid
rsadate
gostdate
docsbuffer

**Comment by sgavrilitsa** [comment]
версия УТМ 4.2.0
1. Положить файл getutminfo.py   \\ip\c$\zabbix\script\
2. Положить файл utmfsrar.conf   \\ip\c$\zabbix\zabbix_agentd.conf.d\  
3. Установить на ПК python-3.9.2-amd64.exe
4. Открыть cmd от имени администратора и выполнить pip install requests
5. Перезапустить службу zabbix
Чтоб заработали Возраст чеков в буфере (час) - необходимо исправить скрипт дописать 
вместо 
    httptext = getUTMUrl(getURL)
    ipnumstr = httptext.rfind("Отсутствуют неотправленные чеки")
исправить на
httptext = getUTMUrl(getURL+'/home')
ipnumstr = httptext.rfind("Отсутствуют неотправленные чеки")

**Comment by askkostya** [comment]
> 3. Установить на ПК python-3.9.2-amd64.exe

Вот тут лежит portable сборка со всеми установленными библиотеками. Необходимо только в PATH указать путь к python.exe https://github.com/askkostya/ZabbixUpdater/tree/master/files/Python

**Comment by sgavrilitsa** [comment]
Спасибо сейчас попробую

**Comment by metex74** [comment]
Привет!
Не подскажешь в чем может быть причина. На Zabbxe в последних данных сообщения такого плана

"python.exe" ?? ???? ????७??? ??? ???譥? ????????, ?ᯮ??塞?? ?ணࠬ??? ??? ?????? 䠩???.
--
по всем элементам данных. В заббиксе не силен, только начинаю изучать. Спасибо

**Comment by Grog01** [comment]
Привет!

УТМ 4.2.0

При выполнении скрипта ошибка:

Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/getutminfo.py", line 44, in <module>
    if sys.argv[1] == "version":
       ~~~~~~~~^^^
IndexError: list index out of range

Помогите разобраться

**Comment by askkostya** [comment]
Привет.
Не передан второй параметр
Второй параметр может принимать значение
version
rsavalid
rsadate
gostdate
docsbuffer

Для примера
getutminfo.py  адресУТМ version

**Comment by Grog01** [comment]
> Привет. Не передан второй параметр Второй параметр может иметь значение принять версию rsavalid rsadate gostdate docsbuffer
> 
> Для примера getutminfo.py адресУТМ версия

Можно подробнее?
С питоном к сожалению не знаком

**Comment by Anarchist123** [comment]
> Привет! Не подскажешь в чем может быть причина. На Zabbxe в последних данных сообщения такого плана
> 
> ## "python.exe" ?? ???? ????७??? ??? ???譥? ????????, ?ᯮ??塞?? ?ணࠬ??? ??? ?????? 䠩???.
> по всем элементам данных. В заббиксе не силен, только начинаю изучать. Спасибо

вы решили эту проблему?   сам скрипт успешно выполняется через IDLE и через CMD...  а в Zabbix агенте никак. Пробовал на Win10x64(python 3.13) и Win7x64 (python 3.8). Path указан.  Аналогичная задача через PowerShell скрипты работает.
